keys:
  # Users
  - &users:
    - &adamr 7813B7E2E0BE0E7DCB1669161058F611DC61E875
  # Hosts
  - &hosts:
    - &msi-nixos age1h5f37l0l9mn24s76mj703y20s65kr7a4ym7xkh55js4gf476fy3sj3hlex
    - &msi-server age1l4pd7yy0qpgvakwec9f8xzcys70q5uf48n7fw6j3p6csryl6lu4qzc6jfh
    - &nixos-htb age1jnu0f6xsh3mdvlxg6vhjd7y5fmx76rghju0l7a3fnjdqd47ju4vqm7vg0x

creation_rules:
  - path_regex: hosts/common/secrets.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *msi-nixos
      - *msi-server
      # - *raspberrypi
      pgp:
      - *adamr

  - path_regex: hosts/msi-nixos/secrets.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *msi-nixos
      pgp:
      - *adamr

  - path_regex: hosts/msi-server/secrets.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *msi-server
      pgp:
      - *adamr

  - path_regex: hosts/nixos-htb/secrets.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *nixos-htb
      pgp:
      - *adamr
