keys:
  # Users
  - &users:
    - &adamr:
      - &yubikey1 D2C3F59395C30CE67FE4991ADCAB4CBA3284E15F
      - &yubikey2 7BC90CBDC348A199BE60955D3DABBE929A3177E9
    - &dani 197E0A55F7BF748AE35B69804FD8819DFE1EF761
  # Hosts
  - &hosts:
    - &msi-nixos age1ny9nuyaxyakpfj3ee3229au4caugv9205leu9vlrfwx4h24fq33qs7jht5
    - &pc age1h5f37l0l9mn24s76mj703y20s65kr7a4ym7xkh55js4gf476fy3sj3hlex
    - &msi-server age1l4pd7yy0qpgvakwec9f8xzcys70q5uf48n7fw6j3p6csryl6lu4qzc6jfh
    - &nixos-htb age1jnu0f6xsh3mdvlxg6vhjd7y5fmx76rghju0l7a3fnjdqd47ju4vqm7vg0x
    - &vm-tests age1mcsvvv2eacr8e9l4umus5hty63waxuhu6kz2j3wwjpracrrx9q7sxnft9w
    - &danix age18840w4w8wn34c4m5p5t72plax24tzc42r44943zgwjl4xwncy3vspceesv

creation_rules:
  - path_regex: hosts/common/secrets.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *msi-nixos
      - *pc
      - *msi-server
      pgp:
      - *yubikey1
      - *yubikey2

  - path_regex: hosts/msi-nixos/secrets.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *msi-nixos
      pgp:
      - *yubikey1
      - *yubikey2

  - path_regex: hosts/pc/secrets.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *pc
      pgp:
      - *yubikey1
      - *yubikey2

    # All files named secrets.<extension> or files with the .sops
    # extension inside msi-server or subfolders
  - path_regex: hosts/msi-server/.*(secrets.(yaml|json|env|ini)|.*.sops)$
    key_groups:
    - age:
      - *msi-server
      pgp:
      - *yubikey1
      - *yubikey2

  - path_regex: hosts/nixos-htb/secrets.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *nixos-htb
      pgp:
      - *yubikey1
      - *yubikey2

  - path_regex: hosts/vm-tests/secrets.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *vm-tests
      pgp:
      - *yubikey1
      - *yubikey2

  - path_regex: hosts/danix/secrets.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *danix
      pgp:
      - *yubikey1
      - *yubikey2

  - path_regex: hosts/common/users/dani/secrets.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *danix
      pgp:
      - *dani
